INSERT INTO Competition(ID, Name, Year, Champion) VALUES (1, 'Liga', 2019, 'UTN Avellaneda')
INSERT INTO Competition(ID, Name, Year, Champion) VALUES (2, 'JUR', 2019, 'UNDAV')
INSERT INTO Competition(ID, Name, Year, Champion) VALUES (3, 'Playoffs', 2019, 'UNQ')

INSERT INTO Team VALUES(1, 'UTN Avellaneda', 'UTN Avellaneda')
INSERT INTO Team VALUES(2, 'UNQ', 'Universidad Nacional de Quilmes')
INSERT INTO Team VALUES(3, 'UNDAV', 'Universidad Nacional de Avellaneda')


INSERT INTO COMPETITION_POSITION VALUES (1, 1, 1)
INSERT INTO COMPETITION_POSITION VALUES (1, 2, 2)
INSERT INTO COMPETITION_POSITION VALUES (1, 3, 3)

INSERT INTO COMPETITION_POSITION VALUES (2, 1, 3)
INSERT INTO COMPETITION_POSITION VALUES (2, 2, 2)
INSERT INTO COMPETITION_POSITION VALUES (2, 3, 1)

INSERT INTO COMPETITION_POSITION VALUES (3, 1, 2)
INSERT INTO COMPETITION_POSITION VALUES (3, 2, 1)
INSERT INTO COMPETITION_POSITION VALUES (3, 3, 3)